version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authentication
  postgres4:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terreplein
  auth-service:
    image: localhost:5000/local-auth:latest
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - redis
      - postgres
      - mongodb_container
volumes:
  mongodb_data_container: